services:
  void-auth: 
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./config:/app/config"
    environment:
      APP_TITLE: VoID Auth

  void-auth-db:
    image: postgres:17
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0cDBZJktmwpe4fIi6534rt4R7vh9TUOL
      # POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
