services:
  void-auth: 
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./config:/app/config"
    environment:
      # Required environment variables
      APP_DOMAIN: # required
      DB_PASSWORD: # required
      DB_HOST: # required
      STORAGE_KEY: # required

      # Not required or has default
      # APP_TITLE: "VoidAuth"
      # APP_COLOR: "#8864c4"
      # SIGNUP: "false"
      # SIGNUP_REQUIRES_APPROVAL: "true"
      # EMAIL_VERIFICATION: "false"
      # DB_PORT: "5432"
      # DB_USER: "postgres"
      # DB_NAME: "postgres"
      # STORAGE_KEY_SECONDARY: 
      # ZXCVBN_MIN: 
      # SMTP_HOST: 
      # SMTP_FROM: 
      # SMTP_PORT: "587"
      # SMTP_SECURE: "false"
      # SMTP_USER: 
      # SMTP_PASS: 

  void-auth-db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: # required
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
